yast/yast-update

- package/yast2-update.changes
- package/yast2-update.spec
- src/clients/update_proposal.rb
Port [bnc#916200](https://bugzilla.suse.com/show_bug.cgi?id=91620) fix to master (PR #40).
- 3.1.27
> Install the packages needed for accessing the installation repository

- package/yast2-update.changes
(required for releasing a maintenance update)
See https://bugzilla.suse.com/show_bug.cgi?id=917896
> Added a BNC number to the changes

- package/yast2-update.changes
- package/yast2-update.spec
- src/clients/packages_proposal.rb
to make the required user action obvious
- 3.1.32
> UX: add a link to the dependency error message (bsc#936450)

- package/yast2-update.changes
- package/yast2-update.spec
- src/modules/RootPart.rb
> Huha snapshot cleanup

- Rakefile
- package/yast2-update.changes
- package/yast2-update.spec
This just a port of #51 to master.
Additional changes:
- Reverted the `Rakefile` SP1 change
- Version `3.1.35`
> Fix products selection (merge SP1 to master)

- .travis.yml
- package/yast2-update.changes
- package/yast2-update.spec
- src/Makefile.am
- src/lib/transfer/file_from_url.rb
- test/Makefile.am
- test/file_from_url_test.rb
- test/io_test.rb
[FATE#316796](https://fate.suse.com/316796)
https://github.com/yast/yast-registration/pull/241
Note the implementation is ugly, because it was simply copied from the other package, and the test is only basic, aiming only to ensure that the move succeded and that the interface works.
I already have better tests (in https://github.com/yast/yast-autoinstallation/pull/193 ) but I first want to get the API in place so that https://github.com/yast/yast-autoinstallation/pull/195 and https://github.com/yast/yast-registration/pull/241 (which is the ultimate goal) can proceed.
After the tests get improved, I want to improve the implementation too.
> Added FileFromUrl

- package/yast2-update.changes
- package/yast2-update.spec
- src/clients/update_proposal.rb
... in the pattern based upgrade.
Manually tested in upgrade SLES11-SP4 -> SLES12-SP2 (the latest build + manual patches).
- 3.1.38
> Select the default product patterns (FATE#320199)

- package/yast2-update.changes
- package/yast2-update.spec
> Updated yast2-packager dependency (FATE#320199)

- package/yast2-update.changes
- package/yast2-update.spec
- src/modules/RootPart.rb
Translate description of Snapper snapshots according to the [solution proposed](https://bugzilla.suse.com/show_bug.cgi?id=988700#c5) by @mvidner to bsc#988700.
> Translate snapper snapshots

- Rakefile
- package/yast2-update.changes
- package/yast2-update.spec
- src/modules/RootPart.rb
Merge `SLE-12-SP2` branch to include fix for [bsc#988700](https://bugzilla.suse.com/show_bug.cgi?id=988700).
> Merge SLE 12 SP2 branch

- .travis.yml
- package/yast2-update.changes
- package/yast2-update.spec
- src/clients/packages_proposal.rb
- test/Makefile.am
- test/packages_proposal_test.rb
Install additional packages during system upgrade. It should fix [bsc#1009834](https://bugzilla.suse.com/show_bug.cgi?id=1009834).
> Install additional packages during upgrade

- package/yast2-update.changes
- src/modules/RootPart.rb
PBI: https://trello.com/c/ZH73v4E1/528-3-storageng-activate-and-probe-inactive-lvm
> Add lvs to list of root partitions

- src/modules/RootPart.rb
File *enum_mappings.rb* was deleted from *yast-storage-ng* because is not longer needed after including *libstorage-ng* wrapper.
In this PR, the usage of *enum_mappings.rb* in *yast-update* in avoided, but the module is not entirely adapted to use the *libstorage-ng* wrapper. Here only are the minimum changes to make openQA runs again for the upgrade process.
> Avoid usage of old enum mappings

- package/yast2-update.changes
- package/yast2-update.spec
- src/modules/RootPart.rb
To be merged right after merging yast2-storage-ng 0.1.32.
> Adapt to cleaned Y2Storage::StorageManager API

- package/yast2-update.changes
- package/yast2-update.spec
- src/modules/RootPart.rb
> Fix typo calling Logger warn method (bsc#1054236)

- package/yast2-update.changes
- package/yast2-update.spec
- src/modules/RootPart.rb
- https://trello.com/c/JONEmkrc
- https://fate.suse.com/323163
> Filter upgradable products in the partition selector already

- package/yast2-update.changes
- package/yast2-update.spec
- src/modules/RootPart.rb
Part of https://trello.com/c/NYy7AklQ/144-5-use-new-libstorage-ng-api-for-mount-points.
> Adapt to new MountPoint API

- package/yast2-update.changes
- package/yast2-update.spec
- src/desktop/update.desktop
Please review the following changes:
* 3bef7ab Merge branch 'SLE-15-GA'
* b3d00e5 Added additional searchkeys to desktop file
> [Review] Request from 'schubi2' @ 'yast/yast-update/review_180629_merged_with_sles15'

- src/modules/RootPart.rb
- test/root_part_test.rb
**IMPORTANT NOTE**: this PR is going to be merged into *pre-SLE-15-SP2* branch. That branch will not be merged into master until *SLE-15-SP1* is branched. Before merging *pre-SLE-15-SP2* branch, a new entry should be added to the changelog (describing all changes provided by *pre-SLE-15-SP2* branch) and the version number should be bumped to *4.2.0*.
Module `RootPart` contains code to adapt fstab and crypttab device names to the new names probed by modern Linux kernel versions. This translation is necessary when upgrading from SLE 9, where device names were `/dev/hdx` and in newer versions the devices are named as `/dev/sdx`.
But for upgrading from SLE 10 on, such translations are not needed anymore. If fact, the key code to perform the translations is only implemented in old …
> Remove device name translations

- package/yast2-update.changes
- package/yast2-update.spec
- src/modules/RootPart.rb
- test/root_part_test.rb
This PR is only for merging *pre-SLE-15-SP2* branch into master once *SLE-15-SP1* has been branched. New entry has been added to the changelog and the version number has been properly bumped (this is the first divergence regarding to SP1).
Original PRs (already reviewed and approved):
* https://github.com/yast/yast-update/pull/120
> Merge pre-SLE-15-SP2

- package/yast2-update.changes
- package/yast2-update.spec
- src/modules/RootPart.rb
- test/root_part_test.rb
Merging #133 (and the whole SLE12-SP5 branch) to master
> Mount /run as /mnt/run to fix LVM (bsc#1152530) - master

- package/yast2-update.changes
- package/yast2-update.spec
- src/include/update/rootpart.rb
- https://jira.suse.com/browse/SLE-7101
- https://trello.com/c/URPtTjGS/1365-5-system-upgrade-using-the-offline-media
- Read the "register_target" value from `control.xml`
- 4.2.9
> Implement upgrade for Full medium (jsc#SLE-7101)

- src/modules/RootPart.rb
- test/root_part_test.rb
https://github.com/yast/yast-update/pull/134 is needed also for SLE15-SP1. See https://github.com/yast/yast-update/pull/133 for more context.
Based on https://github.com/yast/yast-update/pull/134 the code was reworked a bit and unit tests were adjusted.
- changelog etc. after initial review
> mount /run and efivars into target to fix hanging LVM (bsc#1148500)

- package/yast2-update.changes
- package/yast2-update.spec
- src/modules/RootPart.rb
> Fixed too eager Rubocop cleanup

- package/yast2-update.changes
- package/yast2-update.spec
Follow-up to https://github.com/yast/yast-update/pull/138
> release 4.1.11

- package/yast2-update.changes
- package/yast2-update.spec
- src/clients/inst_update_partition.rb
Upgrade process:
Restoring settings if the upgrade process has been aborted by the user.
> Restoring settings if the upgrade process has been aborted by the user.

- .rubocop.yml
- package/yast2-update.changes
- package/yast2-update.spec
- src/modules/RootPart.rb
- test/root_part_test.rb
trello: https://trello.com/c/Oi7jpQi0/1883-drop-old-xml-libraries
unit test included.
> Drop anyxml agent

- package/yast2-update.changes
- package/yast2-update.spec
- src/modules/RootPart.rb
Merge #162 and #163 into the `SLE-15-SP2` branch.
> Merge SLE-15-SP1

- package/yast2-update.changes
- package/yast2-update.spec
- src/modules/RootPart.rb
- test/root_part_test.rb
Backports the fix for [bsc#1180142](bugzilla.suse.com/show_bug.cgi?id=1180142). See https://github.com/yast/yast-update/pull/162. It includes the changes in https://github.com/yast/yast-update/pull/163 too.
> Backports fix for bsc#1180142

- package/yast2-update.changes
- package/yast2-update.spec
- src/modules/RootPart.rb
See https://github.com/yast/yast-update/pull/168.
> Port PR#168 to SLE-15-SP3

- .github/workflows/ci.yml
- Rakefile
See https://github.com/yast/yast-update/pull/168 and https://github.com/yast/yast-update/pull/169.
> Port PR#168 to master (SLE-15-SP4)

- src/include/update/rootpart.rb
- src/lib/update/clients/inst_update_partition_auto.rb
- test/inst_update_partition_auto_test.rb
Adapt the module to the new `ProductSpec` API.
* https://github.com/yast/yast-packager/pull/583
* https://github.com/yast/yast-yast2/pull/1199
> Adapt to the ProductSpec API

- package/yast2-update.changes
- package/yast2-update.spec
- src/include/update/rootpart.rb
- src/lib/update/clients/inst_update_partition_auto.rb
Tentative fix for [bsc#1193212](https://bugzilla.suse.com/show_bug.cgi?id=1193212).
Related PRs:
* https://github.com/yast/yast-packager/pull/595
* https://github.com/yast/yast-yast2/pull/1207
> bsc#1193212: use the ProductSpec API

- package/yast2-update.changes
- package/yast2-update.spec
- src/modules/RootPart.rb
- test/test_helper.rb
- test/update_test.rb
> Merge bsc#1180142 fix into SLE-12-SP4

- package/yast2-update.changes
- package/yast2-update.spec
- src/modules/RootPart.rb
- test/test_helper.rb
- test/update_test.rb
Merge #176 and #177 into `SLE-12-SP5`.
> Merge bsc#1180142 fix into SLE-12-SP5

- package/yast2-update.changes
- package/yast2-update.spec
- src/clients/packages_proposal.rb
- test/packages_proposal_test.rb
- Just merging #184 to the `master` branch
- Added a new unit test
> [master] Warn when removing orphaned 3rd party packages (bsc#1202007)

- package/yast2-update.changes
- package/yast2-update.spec
- src/include/update/rootpart.rb
- Just merging https://github.com/yast/yast-update/pull/186 to `master`
> [master] Rebuild the RPM database during upgrade (--rebuilddb) (bsc#1209565)

- package/yast2-update.changes
- package/yast2-update.spec
- src/include/update/rootpart.rb
- Just backporting https://github.com/yast/yast-update/pull/186 to SLE15-SP3
> [SLE15-SP3] Rebuild the RPM database during upgrade (--rebuilddb) (bsc#1209565)

- package/yast2-update.changes
- package/yast2-update.spec
- src/include/update/rootpart.rb
- Just backporting https://github.com/yast/yast-update/pull/186 to SLE15-SP4
> [SLE15-SP4] Rebuild the RPM database during upgrade (--rebuilddb) (bsc#1209565)

- .rubocop.yml
- package/yast2-update.changes
- package/yast2-update.spec
- src/include/update/rootpart.rb
- Just merging fix #191 from SP5 to SP6
> [SLE15-SP6] Fixed reusing old repositories with new URL

- .rubocop.yml
- Rakefile
- src/clients/backup_proposal.rb
- src/clients/inst_backup.rb
- src/clients/packages_proposal.rb
- src/clients/rootpart_proposal.rb
- src/clients/update_proposal.rb
- src/include/update/rootpart.rb
- src/lib/update/clients/inst_update_partition_auto.rb
- src/modules/RootPart.rb
- src/modules/SUSERelease.rb
- src/modules/Update.rb
- test/update_test.rb
Old version of rubocop start failing, so lets unify versions to the newer one.
trello: https://trello.com/c/8DO6N2t1/3516-update-old-rubocop
Update rubocop version
- *Tested manually*
> Rubocop update
