yast/yast-update

package/yast2-update.changes, package/yast2-update.spec, src/clients/update_proposal.rb
... to have stable output for openQA tests
- Escape the HTML tags
- 3.1.28
=> Sort patterns in the upgrade summary (bsc#931295)

package/yast2-update.changes, package/yast2-update.spec, src/clients/update_proposal.rb, src/modules/Update.rb
The fix is similar to https://github.com/yast/yast-packager/pull/146, fixes [bug #959155](https://bugzilla.suse.com/show_bug.cgi?id=959155).
- Tested manually in a patched installer
- Added/fixed some logging
- Small Rubyfication
Some new products were selected for installation during upgrade:
With this fix applied no new product is selected:
=> Do not select additional products when initializing the update proposal

package/yast2-update.changes, package/yast2-update.spec, src/lib/update/clients/inst_update_partition_auto.rb, test/helpers.rb, test/inst_update_partition_auto_test.rb
This PR is part of the [self update refactorization](https://github.com/yast/yast-installation/pull/422), as the update installer client will be called earlier in the workflow previous fixes are not needed.
=> Update installer is called earlier. Data store is not needed anymore.

.travis.yml, Dockerfile, Rakefile, package/yast2-update.changes, package/yast2-update.spec, src/include/update/rootpart.rb, src/modules/RootPart.rb
See https://trello.com/c/rf9jCXSW/519-5-storageng-upgrade-rootpart-rb-part-1
Tested manually. With this, the upgrade process can go several steps further.
=> RootPart partially adapted to use storage-ng

.gitignore, package/yast2-update.changes, package/yast2-update.spec, src/modules/RootPart.rb
- 3.2.2
This is the same fix as in https://github.com/yast/yast-yast2/pull/570.
=> Fixed parsing whitespace lines in the original /etc/fstab (bsc#1030425)

README.md, package/yast2-update.changes, package/yast2-update.spec, src/include/update/rootpart.rb, src/modules/RootPart.rb, test/test_helper.rb
- trello card: https://trello.com/c/V3v4093v/1014-3-reiserfs-is-dead-manual-upgrade
=> Drop support of reiserfs in a system upgrade (fate#323394)

package/yast2-update.changes, package/yast2-update.spec, src/include/update/rootpart.rb, src/modules/RootPart.rb
Because of this PR yast/yast-storage-ng#335 the partitions using ReiserFS was not shown by default and also shown as a not known linux / Unix partition.
So we have added support for legacy root filesystems in yast/yast-storage-ng#340 and also with this PR the information about the filesystem will be shown in the list although we will block the upgrade if selected and next is pressed (during mount will be detected the presence of legacy filesystems in the fstab)
An autoupgrade will select the only selectable root partition but will detect the presence of legacy root filesystems in the fstab and will show this error:
There will be other error about not able to mount the target system and then the list of selectable partitions will show all the information about the failed one:
=> Show legacy(fate#323394)

package/yast2-update.changes, package/yast2-update.spec, src/modules/RootPart.rb
This is part of https://trello.com/c/lOQcX484/806-bug-1073254-storage-ng-staginge-fails-to-test-upgrade-a-131-installation-to-tw
Depends on this other PR being merged before: https://github.com/yast/yast-storage-ng/pull/473
=> Check by udev names discarded by libstorage-ng (bsc#1073254) 

src/modules/RootPart.rb
Part of https://trello.com/c/lOQcX484/806-bug-1073254-storage-ng-staginge-fails-to-test-upgrade-a-131-installation-to-tw
Not us much as requested, but as far as we can go safely now. Rewriting `RootPart.rb` doesn't sound like such a bad idea.
=> Cleanup leftover comments

package/yast2-update.changes, package/yast2-update.spec, src/modules/RootPart.rb
See https://bugzilla.suse.com/show_bug.cgi?id=1073254
Based on https://github.com/yast/yast-storage-ng/pull/479
I manually tested the 13.1 -> TW upgrade including the three patches (this, https://github.com/yast/yast-storage-ng/pull/479 and https://github.com/yast/yast-bootloader/pull/476) and it worked. :+1:
=> Use the new Devicegraph#find_by_any_name

package/yast2-update.changes, package/yast2-update.spec, src/clients/packages_proposal.rb, src/clients/update_proposal.rb
When the product summary contains a warning save the solver test case for easier debugging. It will be included in the logs collected by `save_y2logs` script.
- See https://bugzilla.suse.com/show_bug.cgi?id=1084248
- 4.0.10
=> Automatically save a solver test case (related to bsc#1084248)

package/yast2-update.changes, package/yast2-update.spec, src/modules/RootPart.rb, src/modules/Update.rb
- Sort the restore scripts alphabetically
- Inject resolv.conf and bind mount the `/dev` to the target chroot so network and the SSL communication with the SCC server works (`/dev/urandom` is need for the encryption).
=> Fixed rollback (bsc#1089643)

package/yast2-update.changes, package/yast2-update.spec, src/modules/RootPart.rb, test/root_part_test.rb
When going back in the upgrade workflow back to the partition selection this error was displayed: ![failed_unmount](https://user-images.githubusercontent.com/907998/39810591-d61d85f0-5385-11e8-8dcb-dc86ed19fc1c.png)
The problem was caused by not unmounting `/mnt/dev`
- This was caused by previous #97 which did not unmount `/mnt/dev` when going back
- Use the same solution as already used for the `/proc` and `/sys` directories (see the diff above the added `MountPartition` call)
- The `AddMountedPartition` remembers the mounted directory and unmounts it when going back
- Tested manually
=> Fixed /mnt/dev unmount

package/yast2-update.changes, package/yast2-update.spec, src/modules/Update.rb
- To mitigate risk of data loss after unexpected reboot/poweroff after aborting upgrade
- See https://bugzilla.suse.com/show_bug.cgi?id=1089643#c60
- 4.0.15
=> Flush the disk cache after restoring the backup (bsc#1089643)

package/yast2-update.changes, package/yast2-update.spec, src/modules/RootPart.rb
PBI: https://trello.com/c/OGssTRzO/393-osdistribution-p2p1-1094963-opensuse-150-installation-or-upgrade-fails-if-disk-contains-encrypted-partition-luks
It requires [this PR](https://github.com/yast/yast-storage-ng/pull/659) be merged.
=> Update encryption names according to crypttab file

package/yast2-update.changes, package/yast2-update.spec, src/modules/Update.rb, test/data/etc/leap-15-os-release, test/data/etc/tw-os-release, test/update_test.rb
> The backup only will be restored when the VERSION_ID matches in both,
the current and backed os-release file.
=>  Do not restore old backups when the upgrade fails

package/yast2-update.changes, package/yast2-update.spec, src/modules/RootPart.rb, test/root_part_test.rb
PBI: https://trello.com/c/bY9jBdVR/424-find-devices-by-uuid
Requires yast-storage-ng 4.1.31, see https://github.com/yast/yast-storage-ng/pull/790
=> Fix upgrade with encrypted partitions

package/yast2-update.changes, package/yast2-update.spec, src/include/update/rootpart.rb, src/modules/RootPart.rb
After migrating to storage-ng, some code in this module is not used anymore. All leftover code should be removed/adapted for both: to simplify base code and to avoid possible bugs.
PBI: https://trello.com/c/Ct6MP1Xz/824-2-clean-up-storage-ng-notes-fixmes-in-yast-update
Leftover code has been removed.
Manually tested
=> Remove obsolete code

package/yast2-update.changes, package/yast2-update.spec, src/clients/update_proposal.rb
when upgrading from SLES12 + SUMA Proxy + SUMA Branch Server
- 4.1.9
=> Uninstall the "SUSE-Manager-Proxy" product (bsc#1133215)

package/yast2-update.changes, package/yast2-update.spec, src/modules/RootPart.rb
The method `Y2Storage::Encryption#save_crypttab_names` was replaced by `Y2Storage::Crypttab#save_encryption_names`.
* Requires https://github.com/yast/yast-storage-ng/pull/969
Code was adapted to use the new API.
=> Adapt to new Crypttab API

package/yast2-update.changes, package/yast2-update.spec, src/modules/RootPart.rb, test/root_part_test.rb
- [bsc#1152530](https://bugzilla.suse.com/show_bug.cgi?id=1152530)
- https://trello.com/c/PN5yWLqx
I've installed SLES12-SP4 and upgraded to SP5 (both unregistered, via DVD).
- used a machine with EFI firmware to test the efivars part of the fix (`qemu-kvm -bios /usr/share/qemu/ovmf-x86_64-ms-code.bin ...` from qemu-ovmf-x86_64.rpm)
- changed the partitioning proposal to propose with LVM, to reproduce the bug and test the fix
=> Mount /run as /mnt/run to fix LVM (bsc#1152530)

package/yast2-update.changes, package/yast2-update.spec, src/clients/packages_proposal.rb, src/clients/update_proposal.rb, src/modules/Update.rb
Replacing old Pkg.ResolvableProperties()and Pkg.ResolvabeDependencies() calls by Y2Packager::Resolvable.any? and Y2Packager::Resolvable.find in order to save memory.
=> Pkg.ResolvableProperties removed

package/yast2-update.changes, package/yast2-update.spec, src/include/update/rootpart.rb
The upgrade process crash when using the online media because `No base product found`
<details>
<summary>Click to show/hide screenshot</summary>
---
</details>
Bugzilla:
* [#1157636](https://bugzilla.suse.com/show_bug.cgi?id=1157636)
* [#1158056](https://bugzilla.suse.com/show_bug.cgi?id=1158056)
Trello:
* https://trello.com/c/pyqFurT6
* https://trello.com/c/Rhvu29XB
Use registration target defined in control.xml also for Online medium like we do for Full medium.
* Tested manually (currently in progress)
=> use control register target also for online update

package/yast2-update.changes, package/yast2-update.spec, src/clients/inst_update_partition.rb, src/modules/RootPart.rb, test/root_part_test.rb
-Aborting upgrade: Restoring old settings e.g. RPM database  (bsc#1158914).
-mount /run and efivars into target to fix hanging LVM (bsc#1148500)
by Steffen Winterfeldt <snwint@suse.com>
This should be a merge with SLES15-SP1 only but it seems there are some missing merges
in https://github.com/yast/yast-update/pull/145/files#diff-609fc4a2ad071e52b49770ed127f87d7
which I have tried to fix. Steffen, Martin could you please check it ?
=> Master bsc 1158914

package/yast2-update.changes, package/yast2-update.spec, src/modules/RootPart.rb, test/root_part_test.rb
- https://bugzilla.suse.com/show_bug.cgi?id=1148500#c38 (and https://bugzilla.suse.com/show_bug.cgi?id=1136463)
- https://trello.com/c/Q3yiDLJ1/1468-3-backport-mounting-run-into-12-sp4-and-15-sp1
and when backporting also backport in same area fix for devfs so now it is basically code from SP5.
=> Backport mounting run

package/yast2-update.changes, package/yast2-update.spec, src/include/update/rootpart.rb
- Related to https://bugzilla.suse.com/show_bug.cgi?id=1159433
- We need to remember the original repositories just after mounting the partition selected to upgrade.
- See also https://github.com/yast/yast-yast2/pull/1010
- Tested manually together with the other changes.
- Fails in Travis because of the new dependency, see https://github.com/yast/yast-yast2/pull/1010
=> Save the original repository setup (bsc#1159433)

package/yast2-update.changes, package/yast2-update.spec, src/clients/update_proposal.rb
This is the fast and easy way to get this into Factory, where is is needed ASAP. Feel free to implement one of the other choices mentioned in bugzilla later on.
=> Also accept Packages.db as valid rpm database (bsc#1162485)

control/update.xml, package/yast2-update.changes, package/yast2-update.spec
https://bugzilla.suse.com/show_bug.cgi?id=1084015
This puts en_US "translations" which are really fixes for broken English or broken translations back into the sources.
```po
#
msgid ""
msgstr ""
"Project-Id-Version: YaST (@memory@)\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2020-01-08 02:29+0000\n"
"PO-Revision-Date: 2002-07-18 14:04+0200\n"
"Last-Translator: proofreader <i18n@suse.de>\n"
"Language-Team: English <i18n@suse.de>\n"
"Language: en_US\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=n != 1;"
#: control/update.glade.translations.glade:9
msgid "Update Configuration"
msgstr "Configure Online Update"
```
I had to reverse-engineer where that message comes from. It turns out that our …
=> Fixed user-visible messages (bsc#1084015)

package/yast2-update.changes, package/yast2-update.spec, src/include/update/rootpart.rb
- Do not remove the initial installation repository
- The `Pkg.SourceRestore` was no operation when a repository was present, to force it to work the workaround was to call `Pkg.SourceFinishAll` to forget all repositories. Unfortunately this caused removing the initial installation repository in openSUSE.
- See related https://github.com/yast/yast-pkg-bindings/pull/125
Note: the spec file change was introduced in the previous PR #150. I wrongly checked in which packages it was, that caused file conflict (https://ci.suse.de/job/yast-yast-update-master/25/console).
=> Fixed repository loading (bsc#1163081)

package/yast2-update.changes, package/yast2-update.spec, src/include/update/rootpart.rb
- Do not remove the installation repositories in the "Previously Used Repositories" step
- https://bugzilla.suse.com/show_bug.cgi?id=1163081
- https://openqa.opensuse.org/tests/1194286#step/upgrade_select/3
- Related to https://github.com/yast/yast-yast2/pull/1030
- Tested manually
- 4.2.18
=> Do not remove the installation repositories (bsc#1163081)

package/yast2-update.changes, package/yast2-update.spec, src/clients/update_proposal.rb
- Fix (or rather a workaround) for bug https://bugzilla.suse.com/show_bug.cgi?id=1176276
- It is an migration from SLE15-SP1 to SLE15-SP2 via an SMT server
- I found this message in the y2log:
`y2packager/resolvable.rb:152 Found several resolvables: [{"transact_by"=>:solver}, {"transact_by"=>:app_high}]`
- That means the [`Resolvable`](https://github.com/yast/yast-yast2/blob/ab3fee8654cb2b7cca315f9d56b260034fa775dd/library/packages/src/lib/y2packager/resolvable.rb#L45) class found two resolvables when lazy loading the requested `transact_by` attribute (the [code](https://github.com/yast/yast-yast2/blob/ab3fee8654cb2b7cca315f9d56b260034fa775dd/library/packages/src/lib/y2packager/resolvable.rb#L161))
- But that's very strange, to later find the original resolvable in libzypp again we …
=> Fixed selecting the base product (bsc#1176276)

test/root_part_test.rb
- Do not read the real `/sys/firmware/efi/efivars` directory from the testing system.
- Related to the previous PR #160, when running `rake osc:sr` on my machine I got this error:
```
received :MountPartition with unexpected arguments
expected: ("/dev", anything, anything, *(any args))
got: ("/sys/firmware/efi/efivars", "efivarfs", "efivarfs")
```
My machine uses EFI so that directory exists and YaST wants to do an extra mount not mocked in the tests.
=> Fixed unit test

package/yast2-update.changes, package/yast2-update.spec, src/modules/RootPart.rb, test/root_part_test.rb
* If creating the snapshot before updating the system fails, the error is reported and handled properly
* Adapt to `FsSnapshot` API changes introduced in https://github.com/yast/yast-yast2/pull/1125.
=> bsc#1180142: do not use 'installation-helper' to create snapshots

src/modules/RootPart.rb
Do not switch the root when creating the pre-snapshot during upgrade. It simplifies #162. See https://github.com/yast/yast-yast2/pull/1138 for context.
=> Do not switch the root when creating the pre-snapshot

package/yast2-update.changes, package/yast2-update.spec, src/clients/update_proposal.rb, src/modules/RootPart.rb, test/root_part_test.rb
=> Merge SLE-15-SP2

package/yast2-update.changes, package/yast2-update.spec, src/modules/RootPart.rb
[bsc#1186895](https://bugzilla.suse.com/show_bug.cgi?id=1186895)
During upgrade, when YaST is inspecting the fstab files, it may happen that one of those files does not contain any valid entry (according to our agent). In such a case, YaST will simply crash.
You can reproduce the problem by writing a `/etc/fstab` file with just a comment (so it is not empty but it does not contain any entry).
This PR prevents such a crash, so YaST can continue analyzing the partition.
=> Do not crash when fstab does not contain any entry

package/yast2-update.changes, package/yast2-update.spec, src/modules/RootPart.rb
The */run* directory is bind-mounted to */mnt/run* twice. This hides submounts from */run*, affecting some upgrade scenarios, specially in an online update.
* https://bugzilla.suse.com/show_bug.cgi?id=1181066
Avoid bind-mount */run* twice.
Manually tested. Now, */run* is bind-mounted once, and the update works (tested Leap 15.1 to Leap 15.2).
=> Bind-mount /run once

package/yast2-update.changes, package/yast2-update.spec, src/clients/update_proposal.rb
- https://bugzilla.suse.com/show_bug.cgi?id=1189590
- Synchronize the YaST repositories to libzypp (save them to the target system)
- This avoids deleting the caches which seems to be unused for libzypp but they are actually still used by YaST
- Tested manually, it seems it needs some specific repository setup in the upgraded system, I could not reproduce the problem with my installed TW. I had to download the disk image with the old system from openQA to reproduce it.
- With the patch the upgrade process does not crash anymore
=> Fixed crash during system upgrade (bsc#1189590)

package/yast2-update.changes, package/yast2-update.spec, src/modules/RootPart.rb, test/test_helper.rb, test/update_test.rb
Backport fix for [bsc#1180142](https://bugzilla.suse.com/show_bug.cgi?id=1180142) to SLE 12 SP3. Please, check #166 for details about the original fix.
Related to:
* https://github.com/yast/yast-yast2/pull/1211
* https://github.com/yast/yast-installation/pull/1003
=> Backport fix for bsc#1180142 to SLE 12

package/yast2-update.changes, package/yast2-update.spec, src/modules/RootPart.rb, test/root_part_test.rb
- A customer uses shared partitions in the system, the offline upgrade might affect the other systems accessing the disk in parallel
- https://bugzilla.suse.com/show_bug.cgi?id=1195894
- https://github.com/yast/yast-update/pull/179
- Use the `norecovery` mount option when searching the root partitions (only for filesystems which support that)
- :heavy_check_mark: Added new unit tests
- :heavy_check_mark: Tested manually
=> Use the "norecovery" mount option (bsc#1195894)

package/yast2-update.changes, package/yast2-update.spec, src/modules/RootPart.rb, test/root_part_test.rb
- https://bugzilla.suse.com/show_bug.cgi?id=1195894
- Use the `norecovery` mount option when searching the root partitions
- Tested manually with Btrfs root partition
=> [SP3] Use the "norecovery" mount option (bsc#1195894)

package/yast2-update.changes, package/yast2-update.spec, src/modules/RootPart.rb, test/root_part_test.rb
- Just merging #179 from SP3 to SP4
- https://bugzilla.suse.com/show_bug.cgi?id=1195894
- Use the `norecovery` mount option when searching the root partitions
=> [SP4] Use the "norecovery" mount option (bsc#1195894)

package/yast2-update.changes, package/yast2-update.spec, src/clients/packages_proposal.rb
- At upgrade the orphaned packages are removed, this might include 3rd party packages like Oracle database
- The removal is silent, no warning is displayed, if user does not check the details in the package manager then a nasty surprise might happen... :rage: 
- https://bugzilla.suse.com/show_bug.cgi?id=1202007
- Display a warning in the upgrade summary with list of removed non-SUSE packages
- In case there are many packages to remove it displays only the first ten ones followed with item "... and more", users can check the full list in the package manager
- This change needs pkg-binding enhancement: https://github.com/yast/yast-pkg-bindings/pull/170
Using this new filtering options we can display a warning in the summary when removing non-SUSE packages:
=> Warn when removing orphaned 3rd party packages (bsc#1202007)

package/yast2-update.changes, package/yast2-update.spec, src/include/update/rootpart.rb
- https://bugzilla.suse.com/show_bug.cgi?id=1209565
- The RPM DB should be rebuilt during upgrade to ensure it is in a consistent state
- Use the new "rebuild_db" option in `Pkg.TargetInitializeOptions()` (https://github.com/yast/yast-pkg-bindings/pull/172)
- Tested manually,  during manual upgrade libzypp calls
```
[zypp::exec++] ExternalProgram.cc(start_program):260 Executing[C] 'rpm' '--root' '/' '--dbpath'
'/mnt/usr/lib/sysimage/rpm' '--rebuilddb' '-vv'
```
=> Rebuild the RPM database during upgrade (--rebuilddb) (bsc#1209565)

package/yast2-update.changes, package/yast2-update.spec
SLE 15 SP6 branch is based on SLE15 SP5 maintenance branch. So fixes done in master can be sometimes useful also for SP6.
just bump version as all master patches are already in SP5
=> Backport SP6

.rubocop.yml, package/yast2-update.changes, package/yast2-update.spec, src/include/update/rootpart.rb
- Just merging fix #191 from SP5 to master
=> [master] Fixed reusing old repositories with new URL

package/yast2-update.changes, package/yast2-update.spec, src/clients/update_proposal.rb
In systems with multiple partitions and systems it is not visible in summary what system/partition will be updated.
trello: https://trello.com/c/8K5XiQej/3522-upgrade-show-the-partition-selected-for-upgrade-in-the-installation-proposal
jira: https://jira.suse.com/browse/PED-3773
Add to Update section line with system and partition that is going to be upgraded.
- *Tested manually*
=> add product update summary to proposal (jsc#PED-3773)
